@section('after_head')
<!--<link rel="stylesheet" type="text/css" href="https://bootswatch.com/bower_components/bootstrap/dist/css/bootstrap.min.css" />-->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />-->
@stop
<div>
    <select name="icon" class="form-control select-icon" data-show-icon="true">
        <option value="0">اختر الايقونه</option>
        <option value="fa-align-left" @if($icon == "fa-align-left")selected @endif>&#xf036; fa-align-left</option>
        <option value="fa-align-right"@if($icon == "fa-align-right")selected @endif>&#xf038; fa-align-right</option>
        <option value="fa-amazon" @if($icon == "fa-amazon")selected @endif >&#xf270; fa-amazon</option>
        <option value="fa-ambulance" @if($icon == "fa-ambulance")selected @endif>&#xf0f9; fa-ambulance</option>
        <option value="fa-anchor" @if($icon == "fa-anchor")selected @endif >&#xf13d; fa-anchor</option>
        <option value="fa-android" @if($icon == "fa-android")selected @endif>&#xf17b; fa-android</option>
        <option value="fa-angellist" @if($icon == "fa-angellist")selected @endif >&#xf209; fa-angellist</option>
        <option value="fa-angle-double-down" @if($icon == "fa-angle-double-down")selected @endif>&#xf103; fa-angle-double-down</option>
        <option value="fa-angle-double-left" @if($icon == "fa-angle-double-left")selected @endif>&#xf100; fa-angle-double-left</option>
        <option value="fa-angle-double-right" @if($icon == "fa-angle-double-right")selected @endif>&#xf101; fa-angle-double-right</option>
        <option value="fa-angle-double-up" @if($icon == "fa-angle-double-up")selected @endif >&#xf102; fa-angle-double-up</option>
        <option value="fa-angle-left" @if($icon == "fa-angle-left")selected @endif>&#xf104; fa-angle-left</option>
        <option value="fa-angle-right" @if($icon == "fa-angle-right")selected @endif >&#xf105; fa-angle-right</option>
        <option value="fa-angle-up" @if($icon == "fa-angle-up")selected @endif >&#xf106; fa-angle-up</option>
        <option value="fa-apple" @if($icon == "fa-apple")selected @endif >&#xf179; fa-apple</option>
        <option value="fa-archive" @if($icon == "fa-archive")selected @endif >&#xf187; fa-archive</option>
        <option value="fa-area-chart" @if($icon == "fa-area-chart")selected @endif >&#xf1fe; fa-area-chart</option>
        <option value="fa-arrow-circle-down" @if($icon == "fa-arrow-circle-down")selected @endif >&#xf0ab; fa-arrow-circle-down</option>
        <option value="fa-arrow-circle-left" @if($icon == "fa-arrow-circle-left")selected @endif >&#xf0a8; fa-arrow-circle-left</option>
        <option value="fa-arrow-circle-o-down" @if($icon == "fa-arrow-circle-o-down")selected @endif >&#xf01a; fa-arrow-circle-o-down</option>
        <option value="fa-arrow-circle-o-left" @if($icon == "fa-arrow-circle-o-left")selected @endif >&#xf190; fa-arrow-circle-o-left</option>
        <option value="fa-arrow-circle-o-right" @if($icon == "fa-arrow-circle-o-right")selected @endif >&#xf18e; fa-arrow-circle-o-right</option>
        <option value="fa-arrow-circle-o-up" @if($icon == "fa-arrow-circle-o-up")selected @endif >&#xf01b; fa-arrow-circle-o-up</option>
        <option value="fa-arrow-circle-right" @if($icon == "fa-arrow-circle-right")selected @endif >&#xf0a9; fa-arrow-circle-right</option>
        <option value="fa-arrow-circle-up" @if($icon == "fa-arrow-circle-up")selected @endif >&#xf0aa; fa-arrow-circle-up</option>
        <option value="fa-arrow-down" @if($icon == "fa-arrow-down")selected @endif >&#xf063; fa-arrow-down</option>
        <option value="fa-arrow-left" @if($icon == "fa-arrow-left")selected @endif >&#xf060; fa-arrow-left</option>
        <option value="fa-arrow-right" @if($icon == "fa-arrow-right")selected @endif >&#xf061; fa-arrow-right</option>
        <option value="fa-arrow-up" @if($icon == "fa-arrow-up")selected @endif >&#xf062; fa-arrow-up</option>
        <option value="fa-arrows" @if($icon == "fa-arrows")selected @endif >&#xf047; fa-arrows</option>
        <option value="fa-arrows-alt" @if($icon == "fa-arrows-alt")selected @endif >&#xf0b2; fa-arrows-alt</option>
        <option value="fa-arrows-h" @if($icon == "fa-arrows-h")selected @endif >&#xf07e; fa-arrows-h</option>
        <option value="fa-arrows-v" @if($icon == "fa-arrows-v")selected @endif >&#xf07d; fa-arrows-v</option>
        <option value="fa-asterisk" @if($icon == "fa-asterisk")selected @endif >&#xf069; fa-asterisk</option>
        <option value="fa-at" @if($icon == "fa-at")selected @endif >&#xf1fa; fa-at</option>
        <option value="fa-automobile" @if($icon == "fa-automobile")selected @endif >&#xf1b9; fa-automobile</option>
        <option value="fa-backward" @if($icon == "fa-backward")selected @endif >&#xf04a; fa-backward</option>
        <option value="fa-balance-scale" @if($icon == "fa-balance-scale")selected @endif >&#xf24e; fa-balance-scale</option>
        <option value="fa-ban" @if($icon == "fa-ban")selected @endif >&#xf05e; fa-ban</option>
        <option value="fa-bank" @if($icon == "fa-bank")selected @endif >&#xf19c; fa-bank</option>
        <option value="fa-bar-chart" @if($icon == "fa-bar-chart")selected @endif >&#xf080; fa-bar-chart</option>
        <option value="fa-bar-chart-o" @if($icon == "fa-bar-chart-o")selected @endif >&#xf080; fa-bar-chart-o</option>
        <option value="fa-battery-full" @if($icon == "fa-battery-full")selected @endif >&#xf240; fa-battery-full</option>
        <option value="fa-beer" @if($icon == "fa-beer")selected @endif >&#xf0fc; fa-beer</option>
        <option value="fa-behance" @if($icon == "fa-behance")selected @endif >&#xf1b4; fa-behance</option>
        <option value="fa-behance-square" @if($icon == "fa-behance-square")selected @endif >&#xf1b5; fa-behance-square</option>
        <option value="fa-bell" @if($icon == "fa-bell")selected @endif >&#xf0f3; fa-bell</option>
        <option value="fa-bell-o" @if($icon == "fa-bell-o")selected @endif >&#xf0a2; fa-bell-o</option>
        <option value="fa-bell-slash" @if($icon == "fa-bell-slash")selected @endif >&#xf1f6; fa-bell-slash</option>
        <option value="fa-bell-slash-o" @if($icon == "fa-bell-slash-o")selected @endif >&#xf1f7; fa-bell-slash-o</option>
        <option value="fa-bicycle" @if($icon == "fa-bicycle")selected @endif >&#xf206; fa-bicycle</option>
        <option value="fa-binoculars" @if($icon == "fa-binoculars")selected @endif >&#xf1e5; fa-binoculars</option>
        <option value="fa-birthday-cake" @if($icon == "fa-birthday-cake")selected @endif >&#xf1fd; fa-birthday-cake</option>
        <option value="fa-bitbucket" @if($icon == "fa-bitbucket")selected @endif >&#xf171; fa-bitbucket</option>
        <option value="fa-bitbucket-square" @if($icon == "fa-bitbucket-square")selected @endif >&#xf172; fa-bitbucket-square</option>
        <option value="fa-bitcoin" @if($icon == "fa-bitcoin")selected @endif >&#xf15a; fa-bitcoin</option>
        <option value="fa-black-tie" @if($icon == "fa-black-tie")selected @endif >&#xf27e; fa-black-tie</option>
        <option value="fa-bold" @if($icon == "fa-bold")selected @endif >&#xf032; fa-bold</option>
        <option value="fa-bolt" @if($icon == "fa-bolt")selected @endif >&#xf0e7; fa-bolt</option>
        <option value="fa-bomb" @if($icon == "fa-bomb")selected @endif >&#xf1e2; fa-bomb</option>
        <option value="fa-book" @if($icon == "fa-book")selected @endif >&#xf02d; fa-book</option>
        <option value="fa-bookmark" @if($icon == "fa-bookmark")selected @endif >&#xf02e; fa-bookmark</option>
        <option value="fa-bookmark-o" @if($icon == "fa-bookmark-o")selected @endif >&#xf097; fa-bookmark-o</option>
        <option value="fa-briefcase" @if($icon == "fa-briefcase")selected @endif >&#xf0b1; fa-briefcase</option>
        <option value="fa-btc" @if($icon == "fa-btc")selected @endif >&#xf15a; fa-btc</option>
        <option value="fa-bug" @if($icon == "fa-bug")selected @endif >&#xf188; fa-bug</option>
        <option value="fa-building" @if($icon == "fa-building")selected @endif >&#xf1ad; fa-building</option>
        <option value="fa-building-o" @if($icon == "fa-building-o")selected @endif >&#xf0f7; fa-building-o</option>
        <option value="fa-bullhorn" @if($icon == "fa-bullhorn")selected @endif >&#xf0a1; fa-bullhorn</option>
        <option value="fa-bullseye" @if($icon == "fa-bullseye")selected @endif >&#xf140; fa-bullseye</option>
        <option value="fa-bus" @if($icon == "fa-bus")selected @endif >&#xf207; fa-bus</option>
        <option value="fa-cab" @if($icon == "fa-cab")selected @endif >&#xf1ba; fa-cab</option>
        <option value="fa-calendar" @if($icon == "fa-calendar")selected @endif >&#xf073; fa-calendar</option>
        <option value="fa-camera" @if($icon == "fa-camera")selected @endif >&#xf030; fa-camera</option>
        <option value="fa-car" @if($icon == "fa-car")selected @endif >&#xf1b9; fa-car</option>
        <option value="fa-caret-up" @if($icon == "fa-caret-up")selected @endif >&#xf0d8; fa-caret-up</option>
        <option value="fa-cart-plus" @if($icon == "fa-cart-plus")selected @endif >&#xf217; fa-cart-plus</option>

        <option value="fa-cc" @if($icon == "fa-cc")selected @endif >&#xf20a; fa-cc</option>
        <option value="fa-cc-amex" @if($icon == "fa-cc-amex")selected @endif >&#xf1f3; fa-cc-amex</option>
        <option value="fa-cc-jcb" @if($icon == "fa-cc-jcb")selected @endif >&#xf24b; fa-cc-jcb</option>
        <option value="fa-cc-paypal" @if($icon == "fa-cc-paypal")selected @endif >&#xf1f4; fa-cc-paypal</option>
        <option value="fa-cc-stripe" @if($icon == "fa-cc-stripe")selected @endif >&#xf1f5; fa-cc-stripe</option>
        <option value="fa-cc-visa" @if($icon == "fa-cc-visa")selected @endif >&#xf1f0; fa-cc-visa</option>
        <option value="fa-chain" @if($icon == "fa-chain")selected @endif >&#xf0c1; fa-chain</option>
        <option value="fa-check" @if($icon == "fa-check")selected @endif >&#xf00c; fa-check</option>
        <option value="fa-chevron-left" @if($icon == "fa-chevron-left")selected @endif >&#xf053; fa-chevron-left</option>
        <option value="fa-chevron-right" @if($icon == "fa-chevron-right")selected @endif >&#xf054; fa-chevron-right</option>
        <option value="fa-chevron-up" @if($icon == "fa-chevron-up")selected @endif >&#xf077; fa-chevron-up</option>
        <option value="fa-child" @if($icon == "fa-child")selected @endif >&#xf1ae; fa-child</option>
        <option value="fa-chrome" @if($icon == "fa-chrome")selected @endif >&#xf268; fa-chrome</option>
        <option value="fa-circle" @if($icon == "fa-circle")selected @endif >&#xf111; fa-circle</option>
        <option value="fa-circle-o" @if($icon == "fa-circle-o")selected @endif >&#xf10c; fa-circle-o</option>
        <option value="fa-circle-o-notch" @if($icon == "fa-circle-o-notch")selected @endif >&#xf1ce; fa-circle-o-notch</option>
        <option value="fa-circle-thin" @if($icon == "fa-circle-thin")selected @endif >&#xf1db; fa-circle-thin</option>
        <option value="fa-clipboard" @if($icon == "fa-clipboard")selected @endif >&#xf0ea; fa-clipboard</option>
        <option value="fa-clock-o" @if($icon == "fa-clock-o")selected @endif >&#xf017; fa-clock-o</option>
        <option value="fa-clone" @if($icon == "fa-clone")selected @endif >&#xf24d; fa-clone</option>
        <option value="fa-close" @if($icon == "fa-close")selected @endif >&#xf00d; fa-close</option>
        <option value="fa-cloud" @if($icon == "fa-cloud")selected @endif >&#xf0c2; fa-cloud</option>
        <option value="fa-cloud-download" @if($icon == "fa-cloud-download")selected @endif >&#xf0ed; fa-cloud-download</option>
        <option value="fa-cloud-upload" @if($icon == "fa-cloud-upload")selected @endif >&#xf0ee; fa-cloud-upload</option>
        <option value="fa-cny" @if($icon == "fa-cny")selected @endif >&#xf157; fa-cny</option>
        <option value="fa-code" @if($icon == "fa-code")selected @endif >&#xf121; fa-code</option>
        <option value="fa-code-fork" @if($icon == "fa-code-fork")selected @endif >&#xf126; fa-code-fork</option>
        <option value="fa-codepen" @if($icon == "fa-codepen")selected @endif >&#xf1cb; fa-codepen</option>
        <option value="fa-coffee" @if($icon == "fa-coffee")selected @endif >&#xf0f4; fa-coffee</option>
        <option value="fa-cog" @if($icon == "fa-cog")selected @endif >&#xf013; fa-cog</option>
        <option value="fa-cogs" @if($icon == "fa-cogs")selected @endif >&#xf085; fa-cogs</option>
        <option value="fa-columns" @if($icon == "fa-columns")selected @endif >&#xf0db; fa-columns</option>
        <option value="fa-comment" @if($icon == "fa-comment")selected @endif >&#xf075; fa-comment</option>
        <option value="fa-comment-o" @if($icon == "fa-comment-o")selected @endif >&#xf0e5; fa-comment-o</option>
        <option value="fa-commenting" @if($icon == "fa-commenting")selected @endif >&#xf27a; fa-commenting</option>
        <option value="fa-commenting-o" @if($icon == "fa-commenting-o")selected @endif >&#xf27b; fa-commenting-o</option>
        <option value="fa-comments" @if($icon == "fa-comments")selected @endif >&#xf086; fa-comments</option>
        <option value="fa-comments-o" @if($icon == "fa-comments-o")selected @endif >&#xf0e6; fa-comments-o</option>
        <option value="fa-compass" @if($icon == "fa-compass")selected @endif >&#xf14e; fa-compass</option>
        <option value="fa-compress" @if($icon == "fa-compress")selected @endif >&#xf066; fa-compress</option>
        <option value="fa-connectdevelop" @if($icon == "fa-connectdevelop")selected @endif >&#xf20e; fa-connectdevelop</option>
        <option value="fa-contao" @if($icon == "fa-contao")selected @endif >&#xf26d; fa-contao</option>
        <option value="fa-copy" @if($icon == "fa-copy")selected @endif >&#xf0c5; fa-copy</option>
        <option value="fa-copyright" @if($icon == "fa-copyright")selected @endif >&#xf1f9; fa-copyright</option>
        <option value="fa-creative-commons" @if($icon == "fa-creative-commons")selected @endif >&#xf25e; fa-creative-commons</option>
        <option value="fa-credit-card" @if($icon == "fa-credit-card")selected @endif >&#xf09d; fa-credit-card</option>
        <option value="fa-crop" @if($icon == "fa-crop")selected @endif >&#xf125; fa-crop</option>
        <option value="fa-crosshairs" @if($icon == "fa-crosshairs")selected @endif >&#xf05b; fa-crosshairs</option>
        <option value="fa-css3" @if($icon == "fa-css3")selected @endif >&#xf13c; fa-css3</option>
        <option value="fa-cube" @if($icon == "fa-cube")selected @endif >&#xf1b2; fa-cube</option>
        <option value="fa-cubes" @if($icon == "fa-cubes")selected @endif >&#xf1b3; fa-cubes</option>
        <option value="fa-cut" @if($icon == "fa-cut")selected @endif >&#xf0c4; fa-cut</option>
        <option value="fa-cutlery" @if($icon == "fa-cutlery")selected @endif >&#xf0f5; fa-cutlery</option>
        <option value="fa-dashboard" @if($icon == "fa-dashboard")selected @endif >&#xf0e4; fa-dashboard</option>
        <option value="fa-dashcube" @if($icon == "fa-dashcube")selected @endif >&#xf210; fa-dashcube</option>
        <option value="fa-database" @if($icon == "fa-database")selected @endif >&#xf1c0; fa-database</option>
        <option value="fa-dedent" @if($icon == "fa-dedent")selected @endif >&#xf03b; fa-dedent</option>
        <option value="fa-delicious" @if($icon == "fa-delicious")selected @endif >&#xf1a5; fa-delicious</option>
        <option value="fa-desktop" @if($icon == "fa-desktop")selected @endif >&#xf108; fa-desktop</option>
        <option value="fa-deviantart" @if($icon == "fa-deviantart")selected @endif >&#xf1bd; fa-deviantart</option>
        <option value="fa-diamond" @if($icon == "fa-diamond")selected @endif >&#xf219; fa-diamond</option>
        <option value="fa-digg" @if($icon == "fa-digg")selected @endif >&#xf1a6; fa-digg</option>
        <option value="fa-dollar" @if($icon == "fa-dollar")selected @endif >&#xf155; fa-dollar</option>
        <option value="fa-download" @if($icon == "fa-download")selected @endif >&#xf019; fa-download</option>
        <option value="fa-dribbble" @if($icon == "fa-dribbble")selected @endif >&#xf17d; fa-dribbble</option>
        <option value="fa-dropbox" @if($icon == "fa-dropbox")selected @endif >&#xf16b; fa-dropbox</option>
        <option value="fa-drupal" @if($icon == "fa-drupal")selected @endif >&#xf1a9; fa-drupal</option>
        <option value="fa-edit" @if($icon == "fa-edit")selected @endif >&#xf044; fa-edit</option>
        <option value="fa-eject" @if($icon == "fa-eject")selected @endif >&#xf052; fa-eject</option>
        <option value="fa-ellipsis-h" @if($icon == "fa-ellipsis-h")selected @endif >&#xf141; fa-ellipsis-h</option>
        <option value="fa-ellipsis-v" @if($icon == "fa-ellipsis-v")selected @endif >&#xf142; fa-ellipsis-v</option>
        <option value="fa-empire" @if($icon == "fa-empire")selected @endif >&#xf1d1; fa-empire</option>
        <option value="fa-envelope" @if($icon == "fa-envelope")selected @endif >&#xf0e0; fa-envelope</option>
        <option value="fa-envelope-o" @if($icon == "fa-envelope-o")selected @endif >&#xf003; fa-envelope-o</option>
        <option value="fa-eur" @if($icon == "fa-eur")selected @endif >&#xf153; fa-eur</option>
        <option value="fa-euro" @if($icon == "fa-euro")selected @endif >&#xf153; fa-euro</option>
        <option value="fa-exchange" @if($icon == "fa-exchange")selected @endif >&#xf0ec; fa-exchange</option>
        <option value="fa-exclamation" @if($icon == "fa-exclamation")selected @endif >&#xf12a; fa-exclamation</option>
        <option value="fa-exclamation-circle" @if($icon == "fa-exclamation-circle")selected @endif >&#xf06a; fa-exclamation-circle</option>
        <option value="fa-exclamation-triangle" @if($icon == "fa-exclamation-triangle")selected @endif >&#xf071; fa-exclamation-triangle</option>
        <option value="fa-expand" @if($icon == "fa-expand")selected @endif >&#xf065; fa-expand</option>
        <option value="fa-expeditedssl" @if($icon == "fa-expeditedssl")selected @endif >&#xf23e; fa-expeditedssl</option>
        <option value="fa-external-link" @if($icon == "fa-external-link")selected @endif >&#xf08e; fa-external-link</option>
        <option value="fa-external-link-square" @if($icon == "fa-external-link-square")selected @endif >&#xf14c; fa-external-link-square</option>
        <option value="fa-eye" @if($icon == "fa-eye")selected @endif >&#xf06e; fa-eye</option>
        <option value="fa-eye-slash" @if($icon == "fa-eye-slash")selected @endif >&#xf070; fa-eye-slash</option>
        <option value="fa-eyedropper" @if($icon == "fa-eyedropper")selected @endif >&#xf1fb; fa-eyedropper</option>
        <option value="fa-facebook" @if($icon == "fa-facebook")selected @endif >&#xf09a; fa-facebook</option>
        <option value="fa-facebook-f" @if($icon == "fa-facebook-f")selected @endif >&#xf09a; fa-facebook-f</option>
        <option value="fa-facebook-official" @if($icon == "fa-facebook-official")selected @endif >&#xf230; fa-facebook-official</option>
        <option value="fa-facebook-square" @if($icon == "fa-facebook-square")selected @endif >&#xf082; fa-facebook-square</option>
        <option value="fa-fast-backward" @if($icon == "fa-fast-backward")selected @endif >&#xf049; fa-fast-backward</option>
        <option value="fa-fast-forward" @if($icon == "fa-fast-forward")selected @endif >&#xf050; fa-fast-forward</option>
        <option value="fa-fax" @if($icon == "fa-fax")selected @endif >&#xf1ac; fa-fax</option>
        <option value="fa-feed" @if($icon == "fa-feed")selected @endif >&#xf09e; fa-feed</option>
        <option value="fa-female" @if($icon == "fa-female")selected @endif >&#xf182; fa-female</option>
        <option value="fa-fighter-jet" @if($icon == "fa-fighter-jet")selected @endif >&#xf0fb; fa-fighter-jet</option>
        <option value="fa-file" @if($icon == "fa-file")selected @endif >&#xf15b; fa-file</option>
        <option value="fa-file-archive-o" @if($icon == "fa-file-archive-o")selected @endif >&#xf1c6; fa-file-archive-o</option>
        <option value="fa-file-audio-o" @if($icon == "fa-file-audio-o")selected @endif >&#xf1c7; fa-file-audio-o</option>
        <option value="fa-file-code-o" @if($icon == "fa-file-code-o")selected @endif >&#xf1c9; fa-file-code-o</option>
        <option value="fa-file-excel-o" @if($icon == "fa-file-excel-o")selected @endif >&#xf1c3; fa-file-excel-o</option>
        <option value="fa-file-image-o" @if($icon == "fa-file-image-o")selected @endif >&#xf1c5; fa-file-image-o</option>
        <option value="fa-file-movie-o" @if($icon == "fa-file-movie-o")selected @endif >&#xf1c8; fa-file-movie-o</option>
        <option value="fa-file-o" @if($icon == "fa-file-o")selected @endif >&#xf016; fa-file-o</option>
        <option value="fa-file-pdf-o" @if($icon == "fa-file-pdf-o")selected @endif >&#xf1c1; fa-file-pdf-o</option>
        <option value="fa-file-photo-o" @if($icon == "fa-file-photo-o")selected @endif >&#xf1c5; fa-file-photo-o</option>
        <option value="fa-file-picture-o" @if($icon == "fa-file-picture-o")selected @endif >&#xf1c5; fa-file-picture-o</option>
        <option value="fa-file-powerpoint-o" @if($icon == "fa-file-powerpoint-o")selected @endif >&#xf1c4; fa-file-powerpoint-o</option>
        <option value="fa-file-sound-o" @if($icon == "fa-file-sound-o")selected @endif >&#xf1c7; fa-file-sound-o</option>
        <option value="fa-file-text" @if($icon == "fa-file-text")selected @endif >&#xf15c; fa-file-text</option>
        <option value="fa-file-text-o" @if($icon == "fa-file-text-o")selected @endif >&#xf0f6; fa-file-text-o</option>
        <option value="fa-file-video-o" @if($icon == "fa-file-video-o")selected @endif >&#xf1c8; fa-file-video-o</option>
        <option value="fa-file-word-o" @if($icon == "fa-file-word-o")selected @endif >&#xf1c2; fa-file-word-o</option>
        <option value="fa-file-zip-o" @if($icon == "fa-file-zip-o")selected @endif >&#xf1c6; fa-file-zip-o</option>
        <option value="fa-files-o" @if($icon == "fa-files-o")selected @endif >&#xf0c5; fa-files-o</option>
        <option value="fa-film" @if($icon == "fa-film")selected @endif >&#xf008; fa-film</option>
        <option value="fa-filter" @if($icon == "fa-filter")selected @endif >&#xf0b0; fa-filter</option>
        <option value="fa-fire" @if($icon == "fa-fire")selected @endif >&#xf06d; fa-fire</option>
        <option value="fa-fire-extinguisher" @if($icon == "fa-fire-extinguisher")selected @endif >&#xf134; fa-fire-extinguisher</option>
        <option value="fa-firefox" @if($icon == "fa-firefox")selected @endif >&#xf269; fa-firefox</option>
        <option value="fa-flag" @if($icon == "fa-flag")selected @endif >&#xf024; fa-flag</option>
        <option value="fa-flag-checkered" @if($icon == "fa-flag-checkered")selected @endif >&#xf11e; fa-flag-checkered</option>
        <option value="fa-flag-o" @if($icon == "fa-flag-o")selected @endif >&#xf11d; fa-flag-o</option>
        <option value="fa-flash" @if($icon == "fa-flash")selected @endif >&#xf0e7; fa-flash</option>
        <option value="fa-flask" @if($icon == "fa-flask")selected @endif >&#xf0c3; fa-flask</option>
        <option value="fa-flickr" @if($icon == "fa-flickr")selected @endif >&#xf16e; fa-flickr</option>
        <option value="fa-floppy-o" @if($icon == "fa-floppy-o")selected @endif >&#xf0c7; fa-floppy-o</option>
        <option value="fa-folder" @if($icon == "fa-folder")selected @endif >&#xf07b; fa-folder</option>
        <option value="fa-folder-o" @if($icon == "fa-folder-o")selected @endif >&#xf114; fa-folder-o</option>
        <option value="fa-folder-open" @if($icon == "fa-folder-open")selected @endif >&#xf07c; fa-folder-open</option>
        <option value="fa-folder-open-o" @if($icon == "fa-folder-open-o")selected @endif >&#xf115; fa-folder-open-o</option>
        <option value="fa-font" @if($icon == "fa-font")selected @endif >&#xf031; fa-font</option>
        <option value="fa-fonticons" @if($icon == "fa-fonticons")selected @endif >&#xf280; fa-fonticons</option>
        <option value="fa-forumbee" @if($icon == "fa-forumbee")selected @endif >&#xf211; fa-forumbee</option>
        <option value="fa-forward" @if($icon == "fa-forward")selected @endif >&#xf04e; fa-forward</option>
        <option value="fa-foursquare" @if($icon == "fa-foursquare")selected @endif >&#xf180; fa-foursquare</option>
        <option value="fa-frown-o" @if($icon == "fa-frown-o")selected @endif >&#xf119; fa-frown-o</option>
        <option value="fa-futbol-o" @if($icon == "fa-futbol-o")selected @endif >&#xf1e3; fa-futbol-o</option>
        <option value="fa-gamepad" @if($icon == "fa-gamepad")selected @endif >&#xf11b; fa-gamepad</option>
        <option value="fa-gavel" @if($icon == "fa-gavel")selected @endif >&#xf0e3; fa-gavel</option>
        <option value="fa-gbp" @if($icon == "fa-gbp")selected @endif >&#xf154; fa-gbp</option>
        <option value="fa-ge" @if($icon == "fa-ge")selected @endif >&#xf1d1; fa-ge</option>
        <option value="fa-gear" @if($icon == "fa-gear")selected @endif >&#xf013; fa-gear</option>
        <option value="fa-gears" @if($icon == "fa-gears")selected @endif >&#xf085; fa-gears</option>
        <option value="fa-genderless" @if($icon == "fa-genderless")selected @endif >&#xf22d; fa-genderless</option>
        <option value="fa-get-pocket" @if($icon == "fa-get-pocket")selected @endif >&#xf265; fa-get-pocket</option>
        <option value="fa-gg" @if($icon == "fa-gg")selected @endif >&#xf260; fa-gg</option>
        <option value="fa-gg-circle" @if($icon == "fa-gg-circle")selected @endif >&#xf261; fa-gg-circle</option>
        <option value="fa-gift" @if($icon == "fa-gift")selected @endif >&#xf06b; fa-gift</option>
        <option value="fa-git" @if($icon == "fa-git")selected @endif >&#xf1d3; fa-git</option>
        <option value="fa-git-square" @if($icon == "fa-git-square")selected @endif >&#xf1d2; fa-git-square</option>
        <option value="fa-github" @if($icon == "fa-github")selected @endif >&#xf09b; fa-github</option>
        <option value="fa-github-alt" @if($icon == "fa-github-alt")selected @endif >&#xf113; fa-github-alt</option>
        <option value="fa-github-square" @if($icon == "fa-github-square")selected @endif >&#xf092; fa-github-square</option>
        <option value="fa-gittip" @if($icon == "fa-gittip")selected @endif >&#xf184; fa-gittip</option>
        <option value="fa-glass" @if($icon == "fa-glass")selected @endif >&#xf000; fa-glass</option>
        <option value="fa-globe" @if($icon == "fa-globe")selected @endif >&#xf0ac; fa-globe</option>
        <option value="fa-google" @if($icon == "fa-google")selected @endif >&#xf1a0; fa-google</option>
        <option value="fa-google-plus" @if($icon == "fa-google-plus")selected @endif >&#xf0d5; fa-google-plus</option>
        <option value="fa-google-plus-square" @if($icon == "fa-google-plus-square")selected @endif >&#xf0d4; fa-google-plus-square</option>
        <option value="fa-google-wallet" @if($icon == "fa-google-wallet")selected @endif >&#xf1ee; fa-google-wallet</option>
        <option value="fa-graduation-cap" @if($icon == "fa-graduation-cap")selected @endif >&#xf19d; fa-graduation-cap</option>
        <option value="fa-gratipay" @if($icon == "fa-gratipay")selected @endif >&#xf184; fa-gratipay</option>
        <option value="fa-group" @if($icon == "fa-group")selected @endif >&#xf0c0; fa-group</option>
        <option value="fa-h-square" @if($icon == "fa-h-square")selected @endif >&#xf0fd; fa-h-square</option>
        <option value="fa-hacker-news" @if($icon == "fa-hacker-news")selected @endif >&#xf1d4; fa-hacker-news</option>
        <option value="fa-hand-grab-o" @if($icon == "fa-hand-grab-o")selected @endif >&#xf255; fa-hand-grab-o</option>
        <option value="fa-hand-lizard-o" @if($icon == "fa-hand-lizard-o")selected @endif >&#xf258; fa-hand-lizard-o</option>
        <option value="fa-hand-o-down" @if($icon == "fa-hand-o-down")selected @endif >&#xf0a7; fa-hand-o-down</option>
        <option value="fa-hand-o-left" @if($icon == "fa-hand-o-left")selected @endif >&#xf0a5; fa-hand-o-left</option>
        <option value="fa-hand-o-right" @if($icon == "fa-hand-o-right")selected @endif >&#xf0a4; fa-hand-o-right</option>
        <option value="fa-hand-o-up" @if($icon == "fa-hand-o-up")selected @endif >&#xf0a6; fa-hand-o-up</option>
        <option value="fa-hand-paper-o" @if($icon == "fa-hand-paper-o")selected @endif >&#xf256; fa-hand-paper-o</option>
        <option value="fa-hand-peace-o" @if($icon == "fa-hand-peace-o")selected @endif >&#xf25b; fa-hand-peace-o</option>
        <option value="fa-hand-pointer-o" @if($icon == "fa-hand-pointer-o")selected @endif >&#xf25a; fa-hand-pointer-o</option>
        <option value="fa-hand-rock-o" @if($icon == "fa-hand-rock-o")selected @endif >&#xf255; fa-hand-rock-o</option>
        <option value="fa-hand-scissors-o" @if($icon == "fa-hand-scissors-o")selected @endif >&#xf257; fa-hand-scissors-o</option>
        <option value="fa-hand-spock-o" @if($icon == "fa-hand-spock-o")selected @endif >&#xf259; fa-hand-spock-o</option>
        <option value="fa-hand-stop-o" @if($icon == "fa-hand-stop-o")selected @endif >&#xf256; fa-hand-stop-o</option>
        <option value="fa-hdd-o" @if($icon == "fa-hdd-o")selected @endif >&#xf0a0; fa-hdd-o</option>
        <option value="fa-header" @if($icon == "fa-header")selected @endif >&#xf1dc; fa-header</option>
        <option value="fa-headphones" @if($icon == "fa-headphones")selected @endif >&#xf025; fa-headphones</option>
        <option value="fa-heart" @if($icon == "fa-heart")selected @endif >&#xf004; fa-heart</option>
        <option value="fa-heart-o" @if($icon == "fa-heart-o")selected @endif >&#xf08a; fa-heart-o</option>
        <option value="fa-heartbeat" @if($icon == "fa-heartbeat")selected @endif >&#xf21e; fa-heartbeat</option>
        <option value="fa-history" @if($icon == "fa-history")selected @endif >&#xf1da; fa-history</option>
        <option value="fa-home" @if($icon == "fa-home")selected @endif >&#xf015; fa-home</option>
        <option value="fa-hospital-o" @if($icon == "fa-hospital-o")selected @endif >&#xf0f8; fa-hospital-o</option>
        <option value="fa-hotel" @if($icon == "fa-hotel")selected @endif >&#xf236; fa-hotel</option>
        <option value="fa-hourglass" @if($icon == "fa-hourglass")selected @endif >&#xf254; fa-hourglass</option>
        <option value="fa-hourglass-1" @if($icon == "fa-hourglass-1")selected @endif >&#xf251; fa-hourglass-1</option>
        <option value="fa-hourglass-2" @if($icon == "fa-hourglass-2")selected @endif >&#xf252; fa-hourglass-2</option>
        <option value="fa-hourglass-3" @if($icon == "fa-hourglass-3")selected @endif >&#xf253; fa-hourglass-3</option>
        <option value="fa-hourglass-end" @if($icon == "fa-hourglass-end")selected @endif >&#xf253; fa-hourglass-end</option>
        <option value="fa-hourglass-half" @if($icon == "fa-hourglass-half")selected @endif >&#xf252; fa-hourglass-half</option>
        <option value="fa-hourglass-o" @if($icon == "fa-hourglass-o")selected @endif >&#xf250; fa-hourglass-o</option>
        <option value="fa-hourglass-start" @if($icon == "fa-hourglass-start")selected @endif >&#xf251; fa-hourglass-start</option>
        <option value="fa-houzz" @if($icon == "fa-houzz")selected @endif >&#xf27c; fa-houzz</option>
        <option value="fa-html5" @if($icon == "fa-html5")selected @endif >&#xf13b; fa-html5</option>
        <option value="fa-i-cursor" @if($icon == "fa-i-cursor")selected @endif >&#xf246; fa-i-cursor</option>
        <option value="fa-ils" @if($icon == "fa-ils")selected @endif >&#xf20b; fa-ils</option>
        <option value="fa-image" @if($icon == "fa-image")selected @endif >&#xf03e; fa-image</option>
        <option value="fa-inbox" @if($icon == "fa-inbox")selected @endif >&#xf01c; fa-inbox</option>
        <option value="fa-indent" @if($icon == "fa-indent")selected @endif >&#xf03c; fa-indent</option>
        <option value="fa-industry" @if($icon == "fa-industry")selected @endif >&#xf275; fa-industry</option>
        <option value="fa-info" @if($icon == "fa-info")selected @endif >&#xf129; fa-info</option>
        <option value="fa-info-circle" @if($icon == "fa-info-circle")selected @endif >&#xf05a; fa-info-circle</option>
        <option value="fa-inr" @if($icon == "fa-inr")selected @endif >&#xf156; fa-inr</option>
        <option value="fa-instagram" @if($icon == "fa-instagram")selected @endif >&#xf16d; fa-instagram</option>
        <option value="fa-institution" @if($icon == "fa-institution")selected @endif >&#xf19c; fa-institution</option>
        <option value="fa-internet-explorer" @if($icon == "fa-internet")selected @endif >&#xf26b; fa-internet-explorer</option>
        <option value="fa-intersex" @if($icon == "fa-intersex")selected @endif >&#xf224; fa-intersex</option>
        <option value="fa-ioxhost" @if($icon == "fa-ioxhost")selected @endif >&#xf208; fa-ioxhost</option>
        <option value="fa-italic" @if($icon == "fa-italic")selected @endif >&#xf033; fa-italic</option>
        <option value="fa-joomla" @if($icon == "fa-joomla")selected @endif >&#xf1aa; fa-joomla</option>
        <option value="fa-jpy" @if($icon == "fa-jpy")selected @endif >&#xf157; fa-jpy</option>
        <option value="fa-jsfiddle" @if($icon == "fa-jsfiddle")selected @endif >&#xf1cc; fa-jsfiddle</option>
        <option value="fa-key" @if($icon == "fa-key")selected @endif >&#xf084; fa-key</option>
        <option value="fa-keyboard-o" @if($icon == "fa-keyboard-o")selected @endif >&#xf11c; fa-keyboard-o</option>
        <option value="fa-krw" @if($icon == "fa-krw")selected @endif >&#xf159; fa-krw</option>
        <option value="fa-language" @if($icon == "fa-language")selected @endif >&#xf1ab; fa-language</option>
        <option value="fa-laptop" @if($icon == "fa-laptop")selected @endif >&#xf109; fa-laptop</option>
        <option value="fa-lastfm" @if($icon == "fa-lastfm")selected @endif >&#xf202; fa-lastfm</option>
        <option value="fa-lastfm-square" @if($icon == "fa-lastfm-square")selected @endif >&#xf203; fa-lastfm-square</option>
        <option value="fa-leaf" @if($icon == "fa-leaf")selected @endif >&#xf06c; fa-leaf</option>
        <option value="fa-leanpub" @if($icon == "fa-leanpub")selected @endif >&#xf212; fa-leanpub</option>
        <option value="fa-legal" @if($icon == "fa-legal")selected @endif >&#xf0e3; fa-legal</option>
        <option value="fa-lemon-o" @if($icon == "fa-lemon-o")selected @endif >&#xf094; fa-lemon-o</option>
        <option value="fa-level-down" @if($icon == "fa-level-down")selected @endif >&#xf149; fa-level-down</option>
        <option value="fa-level-up" @if($icon == "fa-level-up")selected @endif >&#xf148; fa-level-up</option>
        <option value="fa-life-bouy" @if($icon == "fa-life-bouy")selected @endif >&#xf1cd; fa-life-bouy</option>
        <option value="fa-life-buoy" @if($icon == "fa-life-buoy")selected @endif >&#xf1cd; fa-life-buoy</option>
        <option value="fa-life-ring" @if($icon == "fa-life-ring")selected @endif >&#xf1cd; fa-life-ring</option>
        <option value="fa-life-saver" @if($icon == "fa-life-saver")selected @endif >&#xf1cd; fa-life-saver</option>
        <option value="fa-lightbulb-o" @if($icon == "fa-lightbulb-o")selected @endif >&#xf0eb; fa-lightbulb-o</option>
        <option value="fa-line-chart" @if($icon == "fa-line-chart")selected @endif >&#xf201; fa-line-chart</option>
        <option value="fa-link" @if($icon == "fa-link")selected @endif >&#xf0c1; fa-link</option>
        <option value="fa-linkedin" @if($icon == "fa-linkedin")selected @endif >&#xf0e1; fa-linkedin</option>
        <option value="fa-linkedin-square" @if($icon == "fa-linkedin-square")selected @endif >&#xf08c; fa-linkedin-square</option>
        <option value="fa-linux" @if($icon == "fa-linux")selected @endif >&#xf17c; fa-linux</option>
        <option value="fa-list" @if($icon == "fa-list")selected @endif >&#xf03a; fa-list</option>
        <option value="fa-list-alt" @if($icon == "fa-list-alt")selected @endif >&#xf022; fa-list-alt</option>
        <option value="fa-list-ol" @if($icon == "fa-list-ol")selected @endif >&#xf0cb; fa-list-ol</option>
        <option value="fa-list-ul" @if($icon == "fa-list-ul")selected @endif >&#xf0ca; fa-list-ul</option>
        <option value="fa-location-arrow" @if($icon == "fa-location-arrow")selected @endif >&#xf124; fa-location-arrow</option>
        <option value="fa-lock" @if($icon == "fa-lock")selected @endif >&#xf023; fa-lock</option>
        <option value="fa-long-arrow-down" @if($icon == "fa-long-arrow-down")selected @endif >&#xf175; fa-long-arrow-down</option>
        <option value="fa-long-arrow-left" @if($icon == "fa-long-arrow-left")selected @endif >&#xf177; fa-long-arrow-left</option>
        <option value="fa-long-arrow-right" @if($icon == "fa-long-arrow-right")selected @endif >&#xf178; fa-long-arrow-right</option>
        <option value="fa-long-arrow-up" @if($icon == "fa-long-arrow-up")selected @endif >&#xf176; fa-long-arrow-up</option>
        <option value="fa-magic" @if($icon == "fa-magic")selected @endif >&#xf0d0; fa-magic</option>
        <option value="fa-magnet" @if($icon == "fa-magnet")selected @endif >&#xf076; fa-magnet</option>

        <option value="fa-mars-stroke-v" @if($icon == "fa-mars-stroke-v")selected @endif >&#xf22a; fa-mars-stroke-v</option>
        <option value="fa-maxcdn" @if($icon == "fa-maxcdn")selected @endif >&#xf136; fa-maxcdn</option>
        <option value="fa-meanpath" @if($icon == "fa-meanpath")selected @endif >&#xf20c; fa-meanpath</option>
        <option value="fa-medium" @if($icon == "fa-medium")selected @endif >&#xf23a; fa-medium</option>
        <option value="fa-medkit" @if($icon == "fa-medkit")selected @endif >&#xf0fa; fa-medkit</option>
        <option value="fa-meh-o" @if($icon == "fa-meh-o")selected @endif >&#xf11a; fa-meh-o</option>
        <option value="fa-mercury" @if($icon == "fa-mercury")selected @endif >&#xf223; fa-mercury</option>
        <option value="fa-microphone" @if($icon == "fa-microphone")selected @endif >&#xf130; fa-microphone</option>
        <option value="fa-mobile" @if($icon == "fa-mobile")selected @endif >&#xf10b; fa-mobile</option>
        <option value="fa-motorcycle" @if($icon == "fa-motorcycle")selected @endif >&#xf21c; fa-motorcycle</option>
        <option value="fa-mouse-pointer" @if($icon == "fa-mouse-pointer")selected @endif >&#xf245; fa-mouse-pointer</option>
        <option value="fa-music" @if($icon == "fa-music")selected @endif >&#xf001; fa-music</option>
        <option value="fa-navicon" @if($icon == "fa-navicon")selected @endif >&#xf0c9; fa-navicon</option>
        <option value="fa-neuter" @if($icon == "fa-neuter")selected @endif >&#xf22c; fa-neuter</option>
        <option value="fa-newspaper-o" @if($icon == "fa-newspaper-o")selected @endif >&#xf1ea; fa-newspaper-o</option>
        <option value="fa-opencart" @if($icon == "fa-opencart")selected @endif >&#xf23d; fa-opencart</option>
        <option value="fa-openid" @if($icon == "fa-openid")selected @endif >&#xf19b; fa-openid</option>
        <option value="fa-opera" @if($icon == "fa-opera")selected @endif >&#xf26a; fa-opera</option>
        <option value="fa-outdent" @if($icon == "fa-outdent")selected @endif >&#xf03b; fa-outdent</option>
        <option value="fa-pagelines" @if($icon == "fa-pagelines")selected @endif >&#xf18c; fa-pagelines</option>
        <option value="fa-paper-plane-o" @if($icon == "fa-paper-plane-o")selected @endif >&#xf1d9; fa-paper-plane-o</option>
        <option value="fa-paperclip" @if($icon == "fa-paperclip")selected @endif >&#xf0c6; fa-paperclip</option>
        <option value="fa-paragraph" @if($icon == "fa-paragraph")selected @endif >&#xf1dd; fa-paragraph</option>
        <option value="fa-paste" @if($icon == "fa-paste")selected @endif >&#xf0ea; fa-paste</option>
        <option value="fa-pause" @if($icon == "fa-pause")selected @endif >&#xf04c; fa-pause</option>
        <option value="fa-paw" @if($icon == "fa-paw")selected @endif >&#xf1b0; fa-paw</option>
        <option value="fa-paypal" @if($icon == "fa-paypal")selected @endif >&#xf1ed; fa-paypal</option>
        <option value="fa-pencil" @if($icon == "fa-pencil")selected @endif >&#xf040; fa-pencil</option>
        <option value="fa-pencil-square-o" @if($icon == "fa-pencil-square-o")selected @endif >&#xf044; fa-pencil-square-o</option>
        <option value="fa-phone" @if($icon == "fa-phone")selected @endif >&#xf095; fa-phone</option>
        <option value="fa-photo" @if($icon == "fa-photo")selected @endif >&#xf03e; fa-photo</option>
        <option value="fa-picture-o" @if($icon == "fa-picture-o")selected @endif >&#xf03e; fa-picture-o</option>
        <option value="fa-pie-chart" @if($icon == "fa-pie-chart")selected @endif >&#xf200; fa-pie-chart</option>
        <option value="fa-pied-piper" @if($icon == "fa-pied-piper")selected @endif >&#xf1a7; fa-pied-piper</option>
        <option value="fa-pied-piper-alt" @if($icon == "fa-pied-piper-alt")selected @endif >&#xf1a8; fa-pied-piper-alt</option>
        <option value="fa-pinterest" @if($icon == "fa-pinterest")selected @endif >&#xf0d2; fa-pinterest</option>
        <option value="fa-pinterest-p" @if($icon == "fa-pinterest-p")selected @endif >&#xf231; fa-pinterest-p</option>
        <option value="fa-pinterest-square" @if($icon == "fa-pinterest-square")selected @endif >&#xf0d3; fa-pinterest-square</option>
        <option value="fa-plane" @if($icon == "fa-plane")selected @endif >&#xf072; fa-plane</option>
        <option value="fa-play" @if($icon == "fa-play")selected @endif >&#xf04b; fa-play</option>
        <option value="fa-play-circle" @if($icon == "fa-play-circle")selected @endif >&#xf144; fa-play-circle</option>
        <option value="fa-play-circle-o" @if($icon == "fa-play-circle-o")selected @endif >&#xf01d; fa-play-circle-o</option>
        <option value="fa-plug" @if($icon == "fa-plug")selected @endif >&#xf1e6; fa-plug</option>
        <option value="fa-plus" @if($icon == "fa-plus")selected @endif >&#xf067; fa-plus</option>
        <option value="fa-plus-circle" @if($icon == "fa-plus-circle")selected @endif >&#xf055; fa-plus-circle</option>
        <option value="fa-plus-square" @if($icon == "fa-plus-square")selected @endif >&#xf0fe; fa-plus-square</option>
        <option value="fa-plus-square-o" @if($icon == "fa-plus-square-o")selected @endif >&#xf196; fa-plus-square-o</option>
        <option value="fa-power-off" @if($icon == "fa-power-off")selected @endif >&#xf011; fa-power-off</option>
        <option value="fa-print" @if($icon == "fa-print")selected @endif >&#xf02f; fa-print</option>
        <option value="fa-puzzle-piece" @if($icon == "fa-puzzle-piece")selected @endif >&#xf12e; fa-puzzle-piece</option>
        <option value="fa-qq" @if($icon == "fa-qq")selected @endif >&#xf1d6; fa-qq</option>
        <option value="fa-qrcode" @if($icon == "fa-qrcode")selected @endif >&#xf029; fa-qrcode</option>
        <option value="fa-question" @if($icon == "fa-question")selected @endif >&#xf128; fa-question</option>
        <option value="fa-question-circle" @if($icon == "fa-question-circle")selected @endif >&#xf059; fa-question-circle</option>
        <option value="fa-quote-left" @if($icon == "fa-quote-left")selected @endif >&#xf10d; fa-quote-left</option>
        <option value="fa-quote-right" @if($icon == "fa-quote-right")selected @endif >&#xf10e; fa-quote-right</option>
        <option value="fa-ra" @if($icon == "fa-ra")selected @endif >&#xf1d0; fa-ra</option>
        <option value="fa-random" @if($icon == "fa-random")selected @endif >&#xf074; fa-random</option>
        <option value="fa-rebel" @if($icon == "fa-rebel")selected @endif >&#xf1d0; fa-rebel</option>
        <option value="fa-recycle" @if($icon == "fa-recycle")selected @endif >&#xf1b8; fa-recycle</option>
        <option value="fa-reddit" @if($icon == "fa-reddit")selected @endif >&#xf1a1; fa-reddit</option>
        <option value="fa-reddit-square" @if($icon == "fa-reddit-square")selected @endif >&#xf1a2; fa-reddit-square</option>
        <option value="fa-refresh" @if($icon == "fa-refresh")selected @endif >&#xf021; fa-refresh</option>
        <option value="fa-registered" @if($icon == "fa-registered")selected @endif >&#xf25d; fa-registered</option>
        <option value="fa-remove" @if($icon == "fa-remove")selected @endif >&#xf00d; fa-remove</option>
        <option value="fa-renren" @if($icon == "fa-renren")selected @endif >&#xf18b; fa-renren</option>
        <option value="fa-reorder" @if($icon == "fa-reorder")selected @endif >&#xf0c9; fa-reorder</option>
        <option value="fa-repeat" @if($icon == "fa-repeat")selected @endif >&#xf01e; fa-repeat</option>
        <option value="fa-reply" @if($icon == "fa-reply")selected @endif >&#xf112; fa-reply</option>
        <option value="fa-reply-all" @if($icon == "fa-reply-all")selected @endif >&#xf122; fa-reply-all</option>
        <option value="fa-retweet" @if($icon == "fa-retweet")selected @endif >&#xf079; fa-retweet</option>
        <option value="fa-rmb" @if($icon == "fa-rmb")selected @endif >&#xf157; fa-rmb</option>
        <option value="fa-road" @if($icon == "fa-road")selected @endif >&#xf018; fa-road</option>
        <option value="fa-rocket" @if($icon == "fa-rocket")selected @endif >&#xf135; fa-rocket</option>
        <option value="fa-rotate-left" @if($icon == "fa-rocket-left")selected @endif >&#xf0e2; fa-rotate-left</option>
        <option value="fa-rotate-right" @if($icon == "fa-rocket-right")selected @endif >&#xf01e; fa-rotate-right</option>
        <option value="fa-rouble" @if($icon == "fa-rouble")selected @endif >&#xf158; fa-rouble</option>
        <option value="fa-rss" @if($icon == "fa-rss")selected @endif >&#xf09e; fa-rss</option>
        <option value="fa-rss-square" @if($icon == "fa-rss-square")selected @endif >&#xf143; fa-rss-square</option>
        <option value="fa-rub" @if($icon == "fa-rub")selected @endif >&#xf158; fa-rub</option>
        <option value="fa-ruble" @if($icon == "fa-ruble")selected @endif >&#xf158; fa-ruble</option>
        <option value="fa-rupee" @if($icon == "fa-rupee")selected @endif >&#xf156; fa-rupee</option>
        <option value="fa-safari" @if($icon == "fa-safari")selected @endif >&#xf267; fa-safari</option>
        <option value="fa-sliders" @if($icon == "fa-sliders")selected @endif >&#xf1de; fa-sliders</option>
        <option value="fa-slideshare" @if($icon == "fa-slideshare")selected @endif >&#xf1e7; fa-slideshare</option>
        <option value="fa-smile-o" @if($icon == "fa-smile-o")selected @endif >&#xf118; fa-smile-o</option>
        <option value="fa-sort-asc" @if($icon == "fa-sort-asc")selected @endif >&#xf0de; fa-sort-asc</option>
        <option value="fa-sort-desc" @if($icon == "fa-sort-desc")selected @endif >&#xf0dd; fa-sort-desc</option>
        <option value="fa-sort-down" @if($icon == "fa-sort-down")selected @endif >&#xf0dd; fa-sort-down</option>
        <option value="fa-spinner" @if($icon == "fa-spinner")selected @endif >&#xf110; fa-spinner</option>
        <option value="fa-spoon" @if($icon == "fa-spoon")selected @endif >&#xf1b1; fa-spoon</option>
        <option value="fa-spotify" @if($icon == "fa-spotify")selected @endif >&#xf1bc; fa-spotify</option>
        <option value="fa-square" @if($icon == "fa-square")selected @endif >&#xf0c8; fa-square</option>
        <option value="fa-square-o" @if($icon == "fa-square-o")selected @endif >&#xf096; fa-square-o</option>
        <option value="fa-star" @if($icon == "fa-star")selected @endif >&#xf005; fa-star</option>
        <option value="fa-star-half" @if($icon == "fa-star-half")selected @endif >&#xf089; fa-star-half</option>
        <option value="fa-stop" @if($icon == "fa-stop")selected @endif >&#xf04d; fa-stop</option>
        <option value="fa-subscript" @if($icon == "fa-subscript")selected @endif >&#xf12c; fa-subscript</option>
        <option value="fa-tablet" @if($icon == "fa-tablet")selected @endif >&#xf10a; fa-tablet</option>
        <option value="fa-tachometer" @if($icon == "fa-tachometer")selected @endif >&#xf0e4; fa-tachometer</option>
        <option value="fa-tag" @if($icon == "fa-tag")selected @endif >&#xf02b; fa-tag</option>
        <option value="fa-tags" @if($icon == "fa-tags")selected @endif >&#xf02c; fa-tags</option>
    </select>
</div>
